# Deployment da aplicação conversão temperatura

apiVersion: apps/v1
kind: Deployment
metadata:
  name: convertemp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: convertemp
  template:
    metadata:
      labels:
        app: convertemp
    spec:
      containers:
      - name: convertemp
        image: vcolofati/conversao-temperatura:v4
        ports:
        - containerPort: 5000

---
# Service da aplicação conversao de temperatura

apiVersion: v1
kind: Service
metadata:
  name: convertemp
spec:
  selector:
    app: convertemp
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer



  


