# Deployment da aplicação conversão temperatura

apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 5
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
      - name: conversao-temperatura
        image: vcolofati/conversao-temperatura:v7
        ports:
        - containerPort: 8080

---
# Service da aplicação conversao de temperatura

apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer



  


