name: CI-CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
        uses: docker/login-action@v1.12.0
        with:
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USER }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Docker Build and Push
        uses: docker/build-push-action@v2.8.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            vcolofati/conversao-temperatura:latest
            vcolofati/conversao-temperatura:v${{ github.run_number }}
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
        
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.5
        with:
          images: vcolofati/conversao-temperatura:v${{ github.run_number }}
          manifests: |
            k8s/deployment.yaml
